baseurl: https://www.jessicahuynh.info
languageCode: en-us
title: Jessica Huynh
copyright: "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 (CC BY-SA 4.0) International License."

author:
  name: "Jessica Huynh"

pygmentsUseClasses: true
pygmentsCodefences: true

params:
  subtitle: "/hwÉªn/"
  categories: ["Lifestyle","Web development"]
  types: ["post","status","recipe"]
  
taxonomies:
  project: projects
  tag: tags
  category: categor
  
markup:
  tableOfContents:
      endLevel: 4
      ordered: false
      startLevel: 2
  
menu:
  main:
    - name: about
      identifier: about
      url: /about
      weight: -90
    - name: portfolio
      identifier: portfolio
      url: /portfolio
      weight: -80
    - name: blog
      identifier: blog
      url: /blog
      weight: -70
    - name: contact
      identifier: contact
      url: /contact
      weight: -60